version bump

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,7 +25,7 @@ jobs:
       - uses: actions/checkout@v3
       - uses: docker/setup-buildx-action@v2
       - name: Cache Docker layers
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
           path: /tmp/.buildx-cache
           key: ${{ runner.os }}-buildx-${{ github.sha }}
@@ -52,18 +52,11 @@ jobs:
     # needs: [ test ]  # uncomment to require passing tests
     runs-on: ubuntu-22.04
 
-    # A local registry helps us reuse the built image between steps
-    services:
-      registry:
-        image: registry:2
-        ports:
-          - 5000:5000
-
     steps:
       - name: Get git tag
         id: git_info
         if: startsWith(github.ref, 'refs/tags/')
-        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
+        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
       - name: Get project info
         id: determine
         env:
@@ -80,8 +73,8 @@ jobs:
 
           dock_image=$repo:$tag
           echo $dock_image
-          echo "::set-output name=dock_image::$dock_image"
-          echo "::set-output name=repo::$repo"
+          echo "dock_image=$dock_image" >> $GITHUB_OUTPUT
+          echo "repo=$repo" >> $GITHUB_OUTPUT
 
       - uses: actions/checkout@v3
         # QEMU is used for non-x86_64 builds
@@ -92,12 +85,56 @@ jobs:
           driver-opts: network=host
         # cache slightly improves rebuild time
       - name: Cache Docker layers
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
           path: /tmp/.buildx-cache
           key: ${{ runner.os }}-buildx-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-buildx-
+
+        # Here, we want to do the docker build twice:
+        # The first build pushes to our local registry for testing.
+        # The second build pushes to Docker Hub and ghcr.io
+      - name: Build (local only)
+        uses: docker/build-push-action@v3
+        id: docker_build
+        with:
+          context: .
+          file: ./Dockerfile
+          tags: localhost/${{ steps.determine.outputs.dock_image }}
+          load: true
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache
+      # If you have a directory called examples/incoming/ and examples/outgoing/, then
+      # run your ChRIS plugin with no parameters, and asser that it creates all the files
+      # which are expected. File contents are not compared.
+      - name: Run examples
+        id: run_examples
+        run: |
+          if ! [ -d 'examples/incoming/' ] || ! [ -d 'examples/outgoing/' ]; then
+            echo "No examples."
+            exit 0
+          fi
+        
+          dock_image=localhost/${{ steps.determine.outputs.dock_image }}
+          output_dir=$(mktemp -d)
+          cmd=$(docker image inspect -f '{{ (index .Config.Cmd 0) }}' $dock_image)
+          docker run --rm -u "$(id -u):$(id -g)" \
+            -v "$PWD/examples/incoming:/incoming:ro" \
+            -v "$output_dir:/outgoing:rw" \
+            $dock_image $cmd /incoming /outgoing
+          
+          for expected_file in $(find examples/outgoing -type f); do
+            fname="${expected_file##*/}"
+            out_path="$output_dir/$fname"
+            printf "Checking output %s exists..." "$out_path"
+            if [ -f "$out_path" ]; then
+              echo "ok"
+            else
+              echo "not found"
+              exit 1
+            fi
+          done
 
       - name: Login to DockerHub
         id: dockerhub_login
@@ -112,15 +149,13 @@ jobs:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
-
       - name: Build and push
         uses: docker/build-push-action@v3
-        id: docker_build
+        if: github.event_name == 'push' || github.event_name == 'release'
         with:
           context: .
           file: ./Dockerfile
           tags: |
-            localhost:5000/${{ steps.determine.outputs.dock_image }}
             docker.io/${{ steps.determine.outputs.dock_image }}
             ghcr.io/${{ steps.determine.outputs.dock_image }}
           # if non-x86_84 architectures are supported, add them here
@@ -134,12 +169,12 @@ jobs:
         run: |
           repo=${{ steps.determine.outputs.repo }}
           dock_image=${{ steps.determine.outputs.dock_image }}
-          docker run --rm localhost:5000/$dock_image chris_plugin_info > /tmp/description.json
+          docker run --rm localhost/$dock_image chris_plugin_info > /tmp/description.json
           jq < /tmp/description.json  # pretty print in log
-          echo "::set-output name=title::$(jq -r '.title' < /tmp/description.json)"
+          echo "title=$(jq -r '.title' < /tmp/description.json)" >> $GITHUB_OUTPUT
 
       - name: Update DockerHub description
-        uses: peter-evans/dockerhub-description@v2
+        uses: peter-evans/dockerhub-description@v3
         continue-on-error: true  # it is not crucial that this works
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
@@ -147,14 +182,3 @@ jobs:
           short-description: ${{ steps.pluginmeta.outputs.title }}
           readme-filepath: ./README.md
           repository: ${{ steps.determine.outputs.repo }}
-
-      - name: Upload to ChRIS Store
-        id: upload
-        if: github.ref_type == 'tag'
-        uses: FNNDSC/upload-chris-plugin@v1
-        with:
-          description_file: /tmp/description.json
-          username: ${{ secrets.CHRISPROJECT_USERNAME }}
-          password: ${{ secrets.CHRISPROJECT_PASSWORD }}
-          chris_url: https://cube.chrisproject.org/api/v1/
-          compute_names: galena
